language: c
sudo: required
dist: trusty
addons:
  apt:
    update: true
    packages:
    - texlive
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-base
    - texlive-bibtex-extra
    - texlive-extra-utils
    - texlive-fonts-recommended
    - texlive-font-utils
    - texlive-fonts-extra
    - texlive-formats-extra
    - texlive-lang-english
    - texlive-lang-german
    - texlive-science
    - texlive-publishers
    - texlive-pictures
    - latex-xcolor
script:
- make
